
identity="chary"
data-path="/var/lib/besu/data"
genesis-file="/var/lib/config/besu/genesis.json"
logging="DEBUG"
nat-method="AUTO"
tx-pool-retention-hours=999
tx-pool-max-size=1024
p2p-enabled=true
p2p-host="0.0.0.0"
max-peers=25
host-allowlist=["*"]
min-gas-price=0
rpc-http-host="0.0.0.0"
rpc-http-cors-origins=["all"]
metrics-enabled=true
rpc-ws-host="0.0.0.0"
Xdns-enabled=true
Xdns-update-enabled=true
rpc-http-enabled=true
#rpc-http-api="ETH,NET,IBFT,DEBUG,ADMIN,WEB3"
rpc-ws-enabled=true
#rpc-ws-api="ETH,NET,IBFT"
p2p-port=30303
rpc-http-port=8545
rpc-ws-port=8546
discovery-enabled=false